"""remove experience from users

Revision ID: bd29d78c20cc
Revises: 7b209af341c7
Create Date: 2026-04-29 01:18:51.118468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd29d78c20cc'
down_revision: Union[str, Sequence[str], None] = '7b209af341c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'experience_years')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
