"""extend candidate profile

Revision ID: c83f91232d37
Revises: bd29d78c20cc
Create Date: 2026-04-29 01:21:42.193264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83f91232d37'
down_revision: Union[str, Sequence[str], None] = 'bd29d78c20cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('preferred_roles', sa.JSON(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('preferred_locations', sa.JSON(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('expected_ctc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'expected_ctc')
    op.drop_column('candidate_profiles', 'preferred_locations')
    op.drop_column('candidate_profiles', 'preferred_roles')
    # ### end Alembic commands ###
